
common:
  models:
    - name: anymixV2_half.safetensors
      url: https://huggingface.co/x1101/models/resolve/main/anymixV2_half.safetensors
  vae:
    - name: sdxl_vae.safetensors
      url: https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors
    - name: blessed-fix.vae.pt
      url: https://huggingface.co/NoCrypt/blessed_vae/resolve/main/blessed-fix.vae.pt
    - name: nai.vae.pt
      url: https://huggingface.co/ckpt/anything-v3.0/resolve/main/Anything-V3.0.vae.pt
  lora:
    # - name:
    #   url:
  embeddings:
    - name: FastNegativeV2.pt
      url: https://civitai.com/api/download/models/94057?type=Model&format=PickleTensor
    - name: EasyNegative.safetensors
      url: https://huggingface.co/datasets/gsdf/EasyNegative/resolve/main/EasyNegative.safetensors
    - name: negative_hand-neg.pt
      url: https://civitai.com/api/download/models/60938?type=Negative&format=Other
  hypernetwork:
    # - name:
    #   url:
  controlnet:
    # - name:
    #   url:
    
sd:
  extensions:
    - name: sd-webui-controlnet
      url: https://github.com/Mikubill/sd-webui-controlnet
    - name: colab-timer
      url: https://github.com/DEX-1101/timer
    - name: encrypt-img
      url: https://github.com/DEX-1101/sd-encrypt-image
    - name: auto-tag
      url: https://github.com/DEX-1101/auto-tag
    - name: infinite-image-browsing
      url: https://github.com/zanllp/sd-webui-infinite-image-browsing
    - name: batchlink-downloader
      url: https://github.com/etherealxx/batchlinks-webui
    - name: adetailer
      url: https://github.com/Bing-su/adetailer
    - name: regional-prompt
      url: https://github.com/hako-mikan/sd-webui-regional-prompter
    - name: openpose
      url: https://github.com/fkunn1326/openpose-editor
    - name: aspect-ratio
      url: https://github.com/alemelis/sd-webui-ar
    - name: wd-tagger
      url: https://github.com/picobyte/stable-diffusion-webui-wd14-tagger
    - name: civitai-browser-plus
      url: https://github.com/BlafKing/sd-civitai-browser-plus
    - name: tab-ext
      url: https://github.com/Haoming02/sd-webui-tabs-extension
 
  custom_download:
    # - dir:
    #   name:
    #   url:
  config_json:
  ui_config_json:
  env:
    # - --EXAMPLE_ENV=examplevalue
  args:
    # - --example-arg examplevalue
